# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Herdmax < Formula
  desc "Local dev reverse proxy manager for Docker projects"
  homepage "https://github.com/maxcelos/herdmax"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maxcelos/herdmax/releases/download/v0.1.0/herdmax_0.1.0_darwin_amd64.tar.gz"
      sha256 "48f0a4c6d79db25d907e7191b772494d8d6c88f6a9380205652cf9c5c3e7fe2a"

      define_method(:install) do
        bin.install "herdmax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maxcelos/herdmax/releases/download/v0.1.0/herdmax_0.1.0_darwin_arm64.tar.gz"
      sha256 "51d630bbd8c6bdaa47acfa0e0b863d13b8110b29643e716d8782ad8f12398342"

      define_method(:install) do
        bin.install "herdmax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxcelos/herdmax/releases/download/v0.1.0/herdmax_0.1.0_linux_amd64.tar.gz"
      sha256 "ea749b336a632d01b5f7de2a67a4987aaf064a8a8e98f3dcd724b2f978037355"
      define_method(:install) do
        bin.install "herdmax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxcelos/herdmax/releases/download/v0.1.0/herdmax_0.1.0_linux_arm64.tar.gz"
      sha256 "cc5ef47948906873c9ed7559474b66315a018cbb1d2f97799b0549e44e27fb85"
      define_method(:install) do
        bin.install "herdmax"
      end
    end
  end
end
