# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Herdmax < Formula
  desc "Local dev reverse proxy manager for Docker projects"
  homepage "https://github.com/maxcelos/herdmax"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maxcelos/herdmax/releases/download/v0.3.1/herdmax_0.3.1_darwin_amd64.tar.gz"
      sha256 "171baac04144ce68f27f1d81712e110916d3aee5e108ce640484a3a222cfa087"

      define_method(:install) do
        bin.install "herdmax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maxcelos/herdmax/releases/download/v0.3.1/herdmax_0.3.1_darwin_arm64.tar.gz"
      sha256 "83e11defbfd4dfde34647839f87dedb872aedaccf0807a32d9e9091b3285d973"

      define_method(:install) do
        bin.install "herdmax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxcelos/herdmax/releases/download/v0.3.1/herdmax_0.3.1_linux_amd64.tar.gz"
      sha256 "a7c8ed335ff23c0b3214fb7a0417ce8de6def6996baed223133846227ec99a1f"
      define_method(:install) do
        bin.install "herdmax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxcelos/herdmax/releases/download/v0.3.1/herdmax_0.3.1_linux_arm64.tar.gz"
      sha256 "d59a85af8d9e17186d1d69a9796310cc941448172a9118fa2345448db0f720b3"
      define_method(:install) do
        bin.install "herdmax"
      end
    end
  end
end
