# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wpmax < Formula
  desc "Docker-based WordPress site manager"
  homepage "https://github.com/maxcelos/wpmax"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maxcelos/wpmax/releases/download/v0.1.2/wpmax_0.1.2_darwin_amd64.tar.gz"
      sha256 "eaa50a3350e5efd3f817e8a75a5288055a1a054730af6e7044848eb62e300c09"

      define_method(:install) do
        bin.install "wpmax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maxcelos/wpmax/releases/download/v0.1.2/wpmax_0.1.2_darwin_arm64.tar.gz"
      sha256 "09f626757bc54ba33df6960585a7ec2fb242f8831e76311b0321772d77d9684f"

      define_method(:install) do
        bin.install "wpmax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxcelos/wpmax/releases/download/v0.1.2/wpmax_0.1.2_linux_amd64.tar.gz"
      sha256 "9d19d63294170909c080a7d59433e4c91cc5c6676bbd290401d101e8a7443bed"
      define_method(:install) do
        bin.install "wpmax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxcelos/wpmax/releases/download/v0.1.2/wpmax_0.1.2_linux_arm64.tar.gz"
      sha256 "553a2c576877e0953ce0bce8585801305132258ef69c4af54d5f000590521829"
      define_method(:install) do
        bin.install "wpmax"
      end
    end
  end
end
