# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wpmax < Formula
  desc "Docker-based WordPress site manager"
  homepage "https://github.com/maxcelos/wpmax"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maxcelos/wpmax/releases/download/v0.1.5/wpmax_0.1.5_darwin_amd64.tar.gz"
      sha256 "f3c9419469ed95a8a4c1eaa0afdfbb17bce5b359eff7c8259bc0d3077a76b4af"

      define_method(:install) do
        bin.install "wpmax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maxcelos/wpmax/releases/download/v0.1.5/wpmax_0.1.5_darwin_arm64.tar.gz"
      sha256 "0166ebe1fc72de059b54bf44867ecc09df682aa3ca8d77f0df62b92fe52435b4"

      define_method(:install) do
        bin.install "wpmax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxcelos/wpmax/releases/download/v0.1.5/wpmax_0.1.5_linux_amd64.tar.gz"
      sha256 "b0cfe583cd7964fc7436c34b11cf67179697b71d7927bca243fc64e1e7d245b5"
      define_method(:install) do
        bin.install "wpmax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxcelos/wpmax/releases/download/v0.1.5/wpmax_0.1.5_linux_arm64.tar.gz"
      sha256 "e705d515243ef87532879657229617de4bd8917f6bf9e001791b213c972477bc"
      define_method(:install) do
        bin.install "wpmax"
      end
    end
  end
end
