# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdmax" do
  name "herdmax"
  desc "Local dev reverse proxy manager for Docker projects"
  homepage "https://github.com/maxcelos/herdmax"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "herdmax"

  on_macos do
    on_intel do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_darwin_amd64.tar.gz"
      sha256 "924797c968ad6ac5d948e1b29bf8e4fc742192b24f86766666324be1255ceb4f"
    end
    on_arm do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_darwin_arm64.tar.gz"
      sha256 "1c674c723bd96eaefa15a84b5e2fbc92f10f8d70755057c68903cf6d8f7d5f18"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_linux_amd64.tar.gz"
      sha256 "ede029adfa8683a922cddf0bee78e535860a42ce2fe64d3975818f94fc0ba2c8"
    end
    on_arm do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_linux_arm64.tar.gz"
      sha256 "d5ec7c3c8ba6807635caed5db80781b226714ce08ec9dfa2448fdd1e48047061"
    end
  end

  # No zap stanza required
end
