# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdmax" do
  name "herdmax"
  desc "Local dev reverse proxy manager for Docker projects"
  homepage "https://github.com/maxcelos/herdmax"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "herdmax"

  on_macos do
    on_intel do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_darwin_amd64.tar.gz"
      sha256 "4253878e2fa4f0e25dda507e5ab46ee56c7eecb09b14073d7af5c49f6e66c10d"
    end
    on_arm do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_darwin_arm64.tar.gz"
      sha256 "a9ae504ac0147a4889ec3790e0e7adc66aa65190f7a885866148f31fe675c2e0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_linux_amd64.tar.gz"
      sha256 "fc199f2b7f87e8a6cb430bedcbc8841f28bf08bf02bec306e16b64d9a23da38b"
    end
    on_arm do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_linux_arm64.tar.gz"
      sha256 "6aa40b1cbc17b062947218409d2b3b9036d0427de6fe0041a715f348c5cf2875"
    end
  end

  # No zap stanza required
end
