# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdmax" do
  name "herdmax"
  desc "Local dev reverse proxy manager for Docker projects"
  homepage "https://github.com/maxcelos/herdmax"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "herdmax"

  on_macos do
    on_intel do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_darwin_amd64.tar.gz"
      sha256 "b79d1cfed82d44b0e252ab5eb7ca7c5e8692b51f13b6b913cf094f0e2dbbe935"
    end
    on_arm do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_darwin_arm64.tar.gz"
      sha256 "b37073da404de6463de282f96051cecb2847179487450af0d5c6bafe34569c75"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_linux_amd64.tar.gz"
      sha256 "908c8965de1ceca72178a56de7509f1e418f331c9be6d422eef629d4b423b12c"
    end
    on_arm do
      url "https://github.com/maxcelos/herdmax/releases/download/v#{version}/herdmax_#{version}_linux_arm64.tar.gz"
      sha256 "cd4edaec86994ae0a295ce29475f6c34ff8a905096fdb92c4ac599a686b27cc4"
    end
  end

  # No zap stanza required
end
